/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        primary: "#121212",
        secondary: {
          DEFAULT: "#DAA520",
          100: "#FF9001",
          200: "#FF8E01",
          lightblack: "#1E1E1E",
        },
        blackContrast: "#3C3C43",
        txtPrimary: "#E0E0E0",
        txtSecondary: "#939393",
        txtThird: "#757575",
        greenAccent: "#4CAF50",
        redAccent: "#FF5252",

        black: {
          DEFAULT: "#000",
          100: "#1E1E2D",
          200: "#232533",
        },
        gray: {
          100: "#CDCDE0",
        },
      },
      fontFamily: {
        pthin: ["Poppins-Thin", "sans-serif"],
        pextralight: ["Poppins-ExtraLight", "sans-serif"],
        plight: ["Poppins-Light", "sans-serif"],
        pregular: ["Poppins-Regular", "sans-serif"],
        pmedium: ["Poppins-Medium", "sans-serif"],
        psemibold: ["Poppins-SemiBold", "sans-serif"],
        pbold: ["Poppins-Bold", "sans-serif"],
        pextrabold: ["Poppins-ExtraBold", "sans-serif"],
        pblack: ["Poppins-Black", "sans-serif"],
        ithin: ["Inter_18pt-Thin", "sans-serif"],
        ithinitalic: ["Inter_18pt-ThinItalic", "sans-serif"],
        iextralight: ["Inter_18pt-ExtraLight", "sans-serif"],
        iextralightitalic: ["Inter_18pt-ExtraLightItalic", "sans-serif"],
        ilight: ["Inter_18pt-Light", "sans-serif"],
        ilightitalic: ["Inter_18pt-LightItalic", "sans-serif"],
        iregular: ["Inter_18pt-Regular", "sans-serif"],
        iitalic: ["Inter_18pt-Italic", "sans-serif"],
        imedium: ["Inter_18pt-Medium", "sans-serif"],
        imediumitalic: ["Inter_18pt-MediumItalic", "sans-serif"],
        isemibold: ["Inter_18pt-SemiBold", "sans-serif"],
        isemibolditalic: ["Inter_18pt-SemiBoldItalic", "sans-serif"],
        ibold: ["Inter_18pt-Bold", "sans-serif"],
        ibolditalic: ["Inter_18pt-BoldItalic", "sans-serif"],
        iextrabold: ["Inter_18pt-ExtraBold", "sans-serif"],
        iextrabolditalic: ["Inter_18pt-ExtraBoldItalic", "sans-serif"],
        iblack: ["Inter_18pt-Black", "sans-serif"],
        iblackitalic: ["Inter_18pt-BlackItalic", "sans-serif"],
      },
    },
  },
  plugins: [],
};
